version: 2.1

jobs:
  test-build:
    docker:
    - image: connctd/idf-build:latest
    steps:
      - checkout
      - run:
          name: Build test project
          command: |
            source /esp/esp-idf/export.sh && cd test-project && idf.py build
workflows:
  version: 2
  build-image:
    jobs:
      # always do this - keep in mind: branches are included by default, tags excluded by default
      - test-build:
          filters:
            tags:
              only: /^.*/
